# Generated by Django 3.2.5 on 2021-12-03 09:58

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_mdcontent_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdcontent',
            name='textfield',
            field=martor.models.MartorField(),
        ),
    ]
